name: Build

on: 
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: 'pyproject.toml' 
    - name: Install Poetry
      run: |
        pip install poetry
    - name: Validate Environment
      shell: bash
      run: |
        python_version=$(python --version)
        poetry_version=$(poetry --version)

        markdown=$(cat << EOF
        ### Validate Environment
        * Python Version: $python_version
        * Poetry Version: $poetry_version
        EOF
        )
        echo "$markdown" >> $GITHUB_STEP_SUMMARY
