name: Build

on: 
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: 'pyproject.toml' 
    - name: Install Poetry
      run: |
        pip install poetry
    - name: Validate Environment
      shell: bash
      run: |
        python_version=$(python --version)
        poetry_version=$(poetry --version)
        echo "Python Version: $python_version" >> $GITHUB_STEP_SUMMARY
        echo "Poetry Version: $poetry_version" >> $GITHUB_STEP_SUMMARY
